import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HuntingCoders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {"<"}HuntingCoders/{">"}
        </h1>
        <div className={styles.imagewrap}>
          <imt src="/hundingCoders.gif" className={styles.myImg} width={192} height={108} />
        </div>

        <p className={styles.description}>
          A Blog for HuntingCoders by Hunting Coder.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat saepe accusamus assumenda eius corrupti consectetur maxime unde delectus ab ducimus.
        </p>

        <h1 className="grid_h1">Popular Blogs</h1>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Learn JavaScript in 30 Minutes &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
            <button className={styles.btn}>Read More</button>
          </div>

          <div className={styles.card}>
            <h2>Learn JavaScript in 30 Minutes &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
            <button className={styles.btn}>Read More</button>
          </div>

          <div className={styles.card}>
            <h2>Learn JavaScript in 30 Minutes &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>
    </div>
  )
}
